title: Crafting CSS
description: Online handbook for Dylan Beattie’s course “CSS for Engineers”
theme: just-the-docs
host: 0.0.0.0

color_scheme: midnight

url: https://craftingcss.com/

# Suppress Sass deprecation warnings
sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
kramdown:
 math_engine: mathjax
