title: CSS for Engineers
description: Online handbook for Dylan Beattie’s course “CSS for Engineers”
theme: just-the-docs

url: https://ursatile.github.io/css4eng

# Suppress Sass deprecation warnings
sass:
  quiet_deps: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
