title: CSS for Engineers
description: Online handbook for Dylan Beattie’s course “CSS for Engineers”
theme: just-the-docs

color_scheme: dark

url: https://ursatile.github.io/css4eng

# Suppress Sass deprecation warnings
sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
